apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
    - port: 88
      targetPort: 8080  # Assuming vproapp-port is the port exposed by the vproapp container
      protocol: TCP
  selector:
    app: vproapp
  type: LoadBalancer
